function [fitresult, gof] = createGaussianFit(binVaules, normalizedCounts, name, color)
%CREATEFIT(EDGES,NORMALIZEDCOUNTS)
%  Create a fit.
%
%  Data for 'Gaussian Fit' fit:
%      X Input : edges
%      Y Output: normalizedCounts
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 21-Mar-2016 15:50:56


%% Fit: 'Gaussian Fit'.
[xData, yData] = prepareCurveData( binVaules, normalizedCounts );

% Set up fittype and options.
ft = fittype( 'gauss1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf 0];
opts.MaxIter = 1000;
opts.StartPoint = [25.3093363329584 12 2.6628623437039];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Calcuate coeffients
coefficients = coeffvalues(fitresult);
ci = confint(fitresult);
a = coefficients(1); 
b = coefficients(2);
c = coefficients(3);

gof.Amplitude = a; 
gof.Mean = b; 
gof.SD = sqrt(c^2/2); 

gof.Amplitude_ci = ci(:,1)';
gof.Mean_ci = ci(:,2)'; 
gof.SD_ci = sqrt(ci(:,3)' .^2/2);

%% Plot fit with data.
% figure( 'Name', 'Gaussian Fit' );
% subplot( 2, 1, 1 );
fontsize = 28; 
titlesize = 28; 
h = bar( xData, yData, color, 'EdgeColor', color ); hold on    % Plot histogram
f = plot( fitresult, color ); set( f, 'LineWidth', 2 );  % Plot fitcurve
% l = legend( 'Velocity vs. binEdges', 'Gaussian Fit', 'Location', 'NorthEast' );
% set( l, 'FontSize',12 );
set( gca,'XLim', [0 20], 'XTick', 0:5:20, 'fontsize',20 );
set( gca,'YLim', [0 20], 'YTick', 0:5:20, 'fontsize',20 );
% Equation: f(x) =  a1*exp(-((x-b1)/c1)^2)
expfit_str1 = ['y = ' num2str(a, '%.2f') ' * exp(-(x-', num2str(b,'%.2f') '/', num2str(c,'%.2f'),')^2)'];
t1 = text( 10, 14, expfit_str1 );
set( t1, 'FontSize', 16 );
expfit_str2 = ['Mean of Velocity = ' num2str(b) ];
t2 = text( 10, 10, expfit_str2 );
set( t2, 'FontSize', 16 );
% expfit_str3 = ['Adj R^2 = ' num2str(gof.rsquare) ];
% t3 = text( 10, 15, expfit_str3 );
% set( t3, 'FontSize',12 );
xlim( [0, 20] );
ylim( [0, 20] );

% Label axes
xlabel( 'Velocity (um/min)', 'fontsize', fontsize, 'Fontname', 'arial' );
ylabel( 'Frequency distribution (%)', 'fontsize', fontsize, 'Fontname', 'arial' );
title (['Gaussian fit of velocity ', name], 'fontsize', titlesize, 'Fontname', 'arial' );

% % Plot residuals.
% subplot( 2, 1, 2 );
% r = plot( fitresult, xData, yData, 'residuals' );
% set( r, 'MarkerSize', 12 );
% legend( r, 'Gaussian distribution - residuals', 'Zero Line', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'Velocity (um/min)', 'fontsize', 12, 'Fontname', 'arial' );
% ylabel( 'Residuals' );
% 
% print_save_figure( gcf, ['Gaussian_fit_of_', name], 'curve_fit' ); 



