function [fitresult, gof, Best_fit_value] = createExpFit(bin, freq_dist)
%CREATEFIT(BIN,FREQ_DIST)
%  Create a fit.
%
%  Data for 'One phase decay' fit:
%      X Input : bin
%      Y Output: freq_dist
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Mar-2016 14:51:23


%% Fit: 'One phase decay'.
[xData, yData] = prepareCurveData( bin, freq_dist );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.MaxIter = 1000;
opts.StartPoint = [39.0441329254008 -0.131252535995092];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Calcuate coeffients
coefficients = coeffvalues(fitresult);
ci = confint(fitresult);
Y0 = coefficients(1); 
K = - coefficients(2);
Tau = 1/K; 

Best_fit_value.Y0 = Y0; 
Best_fit_value.K = K; 
Best_fit_value.Tau = Tau; 
Best_fit_value.Y0_ci = ci(:,1)'; 
Best_fit_value.K_ci = - ci(:,2)'; 
Best_fit_value.Tau_ci = 1./Best_fit_value.K_ci;  

% Create a figure for the plots.
figure( 'Name', 'One phase decay' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = bar( xData, yData ); hold on    % Plot histogram
f = plot( fitresult ); set( f, 'LineWidth', 2 );  % Plot fitcurve
l = legend( f, 'Nonlinear regression: One phase decay', 'Location', 'NorthEast');
set( l, 'FontSize',12 );
set( gca,'XLim', [2 60], 'XTick', 4:4:60 );
% Equation: y = a * exp(b*x)
expfit_str = ['y = ' num2str(Y0) ' * exp(' num2str(-K) '* x)'];
t = text( 30, 25, expfit_str );
set( t, 'FontSize',12 );

% Label axes
xlabel( 'Lifetimes (sec)', 'fontsize', 12, 'Fontname', 'arial' );
ylabel( 'Frequency Distribution (%)' , 'fontsize', 12, 'Fontname', 'arial' );
title ('One phase decay fitting', 'fontsize', 14, 'Fontname', 'arial' );

% Plot residuals.
subplot( 2, 1, 2 );
r = plot( fitresult, xData, yData, 'residuals' );
set( r, 'MarkerSize', 12 );
legend( r, 'One phase decay - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel( 'Lifetimes (sec)', 'fontsize', 12, 'Fontname', 'arial' );
ylabel( 'Residuals' );


