function [fitresult, gof] = createExpFit(bin, freq_dist, name, color)
%CREATEFIT(BIN,FREQ_DIST)
%  Create a fit.
%
%  Data for 'One phase decay' fit:
%      X Input : bin
%      Y Output: freq_dist
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Mar-2016 14:51:23


%% Fit: 'One phase decay'.
[xData, yData] = prepareCurveData( bin, freq_dist );

% Set up fittype and options.
ft = fittype( 'exp1' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.MaxIter = 1000;
opts.StartPoint = [39.0441329254008 -0.131252535995092];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Calcuate coeffients
coefficients = coeffvalues(fitresult);
ci = confint(fitresult);
Y0 = coefficients(1); 
K = - coefficients(2);
Tau = 1/K; 

gof.Y0 = Y0; 
gof.K = K; 
gof.Tau = Tau; 
gof.Y0_ci = ci(:,1)'; 
gof.K_ci = - ci(:,2)'; 
gof.Tau_ci = 1./gof.K_ci;  

%% Create a figure for the plots.
% figure( 'Name', 'One phase decay' );
fontsize = 28; 
titlesize = 28; 
% Plot fit with data.
% subplot( 2, 1, 1 );
h = bar( xData, yData, color, 'EdgeColor', color );  hold on    % Plot histogram
f = plot( fitresult, color ); set( f, 'LineWidth', 2 ); % Plot fitcurve
% l = legend( f, 'Nonlinear regression: One phase decay', 'Location', 'NorthEast');
% set( l, 'FontSize',12 );
set( gca,'XLim', [2 40], 'XTick', 4:4:40, 'fontsize',20 );
set( gca,'YLim', [0 60], 'YTick', 0:10:60, 'fontsize',20 );
% Equation: y = a * exp(b*x)
expfit_str1 = ['y = ' num2str(Y0) ' * exp(' num2str(-K) '* x)'];
t1 = text( 15, 25, expfit_str1 );
set( t1, 'FontSize', 16 );
expfit_str2 = ['Tau = ' num2str(Tau) ];
t2 = text( 15, 20, expfit_str2 );
set( t2, 'FontSize', 16 );
% expfit_str3 = ['Adj R^2 = ' num2str(gof.rsquare) ];
% t3 = text( 30, 15, expfit_str3 );
% set( t3, 'FontSize',12 );
% Label axes
xlabel( 'Lifetimes (sec)', 'fontsize', fontsize, 'Fontname', 'arial' );
ylabel( 'Frequency Distribution (%)' , 'fontsize', fontsize, 'Fontname', 'arial' );
title (['One phase decay fitting of ', name], 'fontsize', titlesize, 'Fontname', 'arial' );

% % Plot residuals.
% subplot( 2, 1, 2 );
% r = plot( fitresult, xData, yData, 'residuals' );
% set( r, 'MarkerSize', 12 );
% legend( r, 'One phase decay - residuals', 'Zero Line', 'Location', 'NorthEast' );
% % Label axes
% xlabel( 'Lifetimes (sec)', 'fontsize', 12, 'Fontname', 'arial' );
% ylabel( 'Residuals' );
% 
% print_save_figure( gcf, ['Exponential_fit_of_', name], 'curve_fit' ); 
% 



